// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vifxetwhiglgixrkomwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpZnhldHdoaWdsZ2l4cmtvbXd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MzA0NjYsImV4cCI6MjA2MTIwNjQ2Nn0.bfhiRTcusFY-Irpcxhdqoxh7lr7sZPPjTlJ3PEzHsBg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);